project:
  type: website
  output-dir: docs

website:
  title: "Amy Munes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Background
      - Publications

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



